services:
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock
    ports:
      - "8080:8080"
    volumes:
      - wiremock-data:/home/wiremock
    restart: unless-stopped

volumes:
  wiremock-data:
